version: "3"
services:
  acsa_gpu:
    restart: always
    build: .
    ports:
      - "12340:80"
    secrets:
      - tg_bot_token
  redis:
    image: redis
    restart: always
    expose:
      - "6379"
    volumes:
     - db-data:/data

volumes:
  db-data:
  
secrets:
   tg_bot_token:
     file: tg_bot_token.txt